spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true # I have nested services so I need setter injection. Circular References Prohibited by Default in spring boot 2.6 so i need this config.
  servlet:
    multipart:
      max-file-size: 2MB
  mail:
    default-encoding: UTF-8
    protocol: smtp
    test-connection: false
    host: smtp.gmail.com
    port: 587
    username: hr.appeal.app@gmail.com
    password:  # TODO: Don't forget delete when upload to public
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true


springdoc:
  api-docs:
    path: /api-docs