## H2 DB Config
spring:
  main:
    allow-circular-references: true # I have nested services so I need setter injection. Circular References Prohibited by Default in spring boot 2.6 so i need this config.
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:hr-web-app
    username: sa
  servlet:
    multipart:
      max-file-size: 3MB

file-upload:
  storage-path: /home/eren/Downloads/storage

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 60 * 60 * 1000 -> minute, second, ms
