spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:hr-web-app
    username: sa

file-upload:
  storage-path: /home/eren/Downloads/storage